apiVersion: apps/v1
kind: Deployment
metadata:
name: echobot
spec:
replicas: 4
strategy:
rollingUpdate:
maxSurge: 1
maxUnavailable: 1
minReadySeconds: 30
template:
metadata:
labels:
app: echobot
spec:
containers:
- name: echobot
image: dkaminfotech/echobot:latest
ports:
- containerPort: 80
- containerPort: 3978
- containerPort: 443
resources:
requests:
cpu: 250m
limits:
cpu: 500m
env:
- name: DB_IfAny
value: "Well_I_Dont_Have_One"
---
apiVersion: v1
kind: Service
metadata:
name: echobot
spec:
type: LoadBalancer
ports:
- port: 80
- port: 3978
- port: 443
selector:
app: echobot