apiVersion: apps/v1
kind: Deployment
metadata:
name: echobot
spec:
type: LoadBalancer
replicas: 4
strategy:
rollingUpdate:
maxSurge: 1
maxUnavailable: 1
minReadySeconds: 30
template:
metadata:
labels:
app: echobot
spec:
containers:
- name: echobot
image: dkaminfotech/echobot:latest
ports:
- containerPort: 80
- containerPort: 3978
- containerPort: 443
resources:
requests:
cpu: 250m
limits:
cpu: 500m